routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function () {

    Route::resource('teams', 'TeamsController');

    Route::get('projects/create/{team_id?}', 'ProjectsController@create');
    Route::post('tasks/create/{project_id?}', 'TasksController@create');
    Route::post('/projects/adduser', 'ProjectsController@adduser')->name('projects.adduser');
    Route::post('/teams/adduser', 'TeamsController@adduser')->name('teams.adduser');
    Route::resource('projects', 'ProjectsController');
    
    Route::resource('roles', 'RolesController');
    Route::resource('tasks', 'TasksController');
    Route::resource('users', 'UsersController');
    Route::resource('comments', 'CommentsController');
    Route::resource('addmember', 'AddmembersController');

    
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    //
	protected $fillable = [
    	'title',
    	'description',
    	'priority',
    	'start_date',
    	'finish_date',
    	'team_id',
    	'user_id'
    ];

    public function users(){
        return $this->belongsToMany('App\User');
    }

    public function team(){
        return $this->belongsTo('App\Team');
    }

    public function comments(){
        return $this->morphMany('App\Comment', 'commentable');
    }
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Project;
use App\ProjectUser;
use App\Team;
use App\User;
use Illuminate\Support\Facades\Auth;

class ProjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $projects = Project::all();

        return view('projects.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($team_id = null)
    {
        //
        $teams = Team::all();

        return view('projects.create', ['project_id'=>$team_id], compact('teams'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        Project::create($request->all());

        return redirect('/home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        //
        // $team = Team::where('id', $team->id )->first();
        $project = Project::find($project->id);

        return view('projects.show', compact('project'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $teams = Team::all();
        $project = Project::findOrFail($id);

        return view('projects.edit', compact('project', 'teams'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $project = Project::findOrFail($id);

        $team = Team::findOrFail($id);

        $project->update($request->all());

        $team->update($request->all());

        return redirect('/home');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $project = Project::whereId($id)->delete();

        return redirect('/projects');
    }

    public function adduser(Request $request){
         //add user to projects 

         //take a project, add a user to it
         $project = Project::find($request->input('id'));

        

         if(Auth::user()->id == $project->id){

         $user = User::where('email', $request->input('email'))->first(); //single record

         //check if user is already added to the project
         // $projectUser = ProjectUser::where('user_id',$user->id)
         //                            ->where('project_id',$project->id)
         //                            ->first();
                                    
         //    if($projectUser){
         //        //if user already exists, exit 
        
         //        return response()->json(['success' ,  $request->input('email').' is already a member of this project']); 
               
         //    }


            if($user && $project){

                $project->users()->attach($user->id); 

                     return response()->json(['success' ,  $request->input('email').' was added to the project successfully']); 
                        
                    }
                    
         }

         return redirect()->route('projects.show', ['project'=> $project->id])
         ->with('errors' ,  'Error adding user to project');
        

         
     }
}

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create Project</div>

                <div class="card-body">
                	<form method="post" action="/projects">
                		{{csrf_field()}}
                		Project name: <input type="text" name="title"><br><br>
                		Project description: <input type="text" name="description"><br><br>
                		Select Team: <select id="team_id" name="team_id" class="form-control">
                			<option>-----Select Team-----</option>
                			@foreach($teams as $team)
                				<option value="{{$team->id}}">{{$team->name}}</option>
                			@endforeach
                		</select>
                		Priority: <input type="text" name="priority"><br><br>
                		Start date: <input type="date" name="start_date"><br><br>
                		Finish date: <input type="date" name="finish_date"><br><br>
                		<input type="submit" class="btn btn-default" value="submit">
                	</form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Project</div>

                <div class="card-body">
                	<form method="post" action="/projects/{{$project->id}}">
                		{{csrf_field()}}
                        <input type="hidden" name="_method" value="PUT">
                        Project name: <input type="text" name="title" value="{{$project->title}}"><br><br>
                        Project description: <input type="text" name="description" value="{{$project->description}}"><br><br>
                        Select Team: <select id="team_id" name="team_id" class="form-control">
                            <option>-----Select Team-----</option>
                            @foreach($teams as $team)
                                <option value="{{$team->id}}">{{$team->name}}</option>
                            @endforeach
                        </select>
                        Priority: <input type="text" name="priority" value="{{$project->priority}}"><br><br>
                        Start date: <input type="date" name="start_date" value="{{$project->start_date}}"><br><br>
                        Finish date: <input type="date" name="finish_date" value="{{$project->finish_date}}"><br><br>
                		<input type="submit" class="btn btn-default" value="submit">
                	</form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Projects</div>

                <div class="card-body">
                    <div class="card text-center"><a class="btn btn-default text-left" href="/projects/create">Create new project</a></div>
                  <div class="list-group">
                        <hr>
                        @foreach($projects as $project)
                            <a href="/projects/{{$project->id}}" class="list-group-item"> {{$project->title}} </a>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
          </p>
          <div class="jumbotron">
            <h1> {{$project->title}} </h1>
            <p> {{$project->description}} </p>
          </div>
          <div class="row">
            <div class="col-md-12 col-lg-12 col-sm-12" style="background: white;">

        
            <!-- Fluid width widget -->   
            <br>     
          <div class="card">
                    <h3 class="card-header">
                        <span class="glyphicon glyphicon-message"></span> 
                        Recent Comments
                    </h3>
                <div class="card-body">
                    <ul class="media-list">
                        @foreach($project->comments as $comment)
                        <li class="media">
                            <div class="media-body">
                                <h4 class="media-heading">
                                    <small>
                                        <a href="users/{{$comment->user->id}}"> - {{$comment->user->email}} </a>
                                        <br>
                                        commented on <a href="#">{{$comment->created_at->diffForHumans() }}</a>
                                    </small>
                                </h4>
                                <p>
                                    {{ $comment->body }}
                                </p>
                                <b>Proof:</b>
                                <p>
                                    {{ $comment->url }}
                                </p>
                            </div>
                        </li>
                        <hr>
                        @endforeach
                    </ul>
                </div>
            </div>
            <!-- End fluid width widget --> 
          
              <form method="post" action="{{route('comments.store')}}">
                {{csrf_field()}}

                <input type="hidden" name="commentable_type" value="App\Project">
                <input type="hidden" name="commentable_id" value="{{$project->id}}">

                <div class="form-group">
                  <label for="comment-content">Comment</label>
                  <textarea placeholder="Enter comments" style="resize: vertical" id="comment-content" name="body" rows="3" spellcheck="false" class="form-control autosize-target text-left"> 
                  
                  </textarea>
                </div>

                <div class="form-group">
                  <label for="team-content">Proof of work done (URL/Photos)</label>
                  <textarea placeholder="Enter url or screenshots" style="resize: vertical" id="team-content" name="url" rows="2" spellcheck="false" class="form-control autosize-target text-left"> 
                  
                  </textarea>
                </div>

                <div class="form-group">
                  <input type="submit" class="btn btn-default" value="submit">
                </div>

              </form>
            </div>
          </div><!--/row-->
          <br>

        </div><!--/.col-xs-12.col-sm-9-->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
         <!--  <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div> -->
            <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
              <li><a href="/projects/{{$project->id}}/edit">Edit</a></li>
              <li><a href="/projects/create">Create new project</a></li>
              <li><a href="/projects">My projects</a></li>

              <br/>

              <li>
              </form>
              <form method="post" action="/projects/{{$project->id}}">
                  {{csrf_field()}}
                  <input type="hidden" name="_method" value="DELETE">
                  <input type="submit" class="btn btn-default" value="Delete">
                  </form></li>

              </li>
            </ol>

          <!-- <hr>
          <h4>Add Members</h4>
          <div class="row">
            <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
              <form id="add-user" action="{{route('projects.adduser')}}" method="post"> 
                {{csrf_field()}}
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Email">
                <span class="input-group-btn">
                  <button class="btn btn-default" type="submit">Add</button>
                </span>
              </div>
            </form>
            </div>
          </div>

            <br>
             <h4>Team members</h4>
            <ol class="list-unstyled">
              @foreach($project->users as $user)
              <li><a href="#">{{$user->email}}</a></li>
              @endforeach
            </ol>
 -->
          </div>
    <!--       <div class="sidebar-module">
            <h4>Members</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
            </ol>
          </div> -->
        </div>

      <hr>


    </div>
@endsection